provider:
  name: faas
  gateway: http://127.0.0.1:8080/

functions:
  gitrepocount:
    lang: go
    handler: ./gitrepocount
    image: kacole2/gitrepocount:0.0.4
    secrets:
      - github-api-secret
